name: app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^2.0.0
  cupertino_icons: ^0.1.3
  flutter_svg: ^0.17.4
  http: ^0.12.0+4
  json_annotation: ^3.0.1
  flutter_screenutil: ^1.1.0
  google_fonts: ^0.5.0+1
  image_picker: ^0.6.5
  multi_image_picker: ^4.6.6+rc.1

dev_dependencies:
  build_runner: ^1.8.1
  json_serializable: ^3.3.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/image/
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf