/// Flutter icons CustomIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const _kFontPkg = null;

  static const IconData union = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_6_1 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData picture_1 = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mirror_1 = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lamp_1 = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData desk_chair_1 = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wardrobe_1 = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cabinet_1 = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bed_1 = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chair_1 = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sofa_1 = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData xmlid_439 = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData currency_rates_2 = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData xmlid_439__1_ = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData broom_1 = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_1 = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_black = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData post = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_black = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cross = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cross_gray = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delievery = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_1 = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_yellow = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back_1 = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData currency = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dollar = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rmb = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData x = IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more = IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData setting = IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share_1 = IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData verified = IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
